### ISSUE TITLE
Wrong File Format Version in VS2010 sln

### ISSUE THREAD

**Issue by KiraSlith** [kiyolee/apr-win-build#1]
File \build-VS2010\apr.sln
"Microsoft Visual Studio Solution File, Format Version 12.00"
needs to be changed to 
"Microsoft Visual Studio Solution File, Format Version 11.00"
in order to open in Visual Studio 2010

Otherwise it builds just fine. Thanks for repackaging the build tools for ease of use!

**Comment by kiyolee** [comment]
Somehow my VS2010 installation handles the solution files just fine.
However, the format version is better be accurate.
Thanks for reporting that.
